### ISSUE TITLE
Storing data without permission

### ISSUE THREAD

**Issue by isitreallyalive** [johann-lr/discord-stats#1]
Isn't that kind of a red flag? Maybe you could add some way to enable or disable it per user? Some people don't like this type of stuff, and their privacy should not be controlled by a server's owner. If they want it, they should be able to enable it.

Also, it is kind of against the TOS, so...

**Comment by johann-lr** [comment]
Thanks... I solved it by just adding the bot to one channel where you can get access for if you want, but it would be better like that I think :)
Going to add it soon!

**Comment by isitreallyalive** [comment]
Nice!
